"""
ML-Assisted Benders Decomposition for p-Hub-Arc Problem

This implementation keeps the original Benders method exact.

ML is used only for:
1. Predicting promising hub arcs for warm start.
2. Ranking OD pairs during callback separation.
3. Optionally ranking generated cuts.

Exactness is preserved because:
- all Benders cuts are still generated by the exact dual separation algorithm;
- if ML-prioritized OD pairs do not generate cuts, the callback runs full separation.
"""

import math
import statistics
import time
from typing import Any, Dict, List, Optional, Tuple

import gurobipy as gp
from gurobipy import GRB

try:
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    import joblib

    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

from algo1_hub_arc import separation_algorithm_dual
from algo3_hub_arc import (
    compute_allocation_cost,
    phase1_solve_mp,
)


# ============================================================
# 1. Preprocessing
# ============================================================

def preprocess(n: int, W: List[List[float]], D: List[List[float]]):
    """
    Build C, L, K, cost_map, arcs_sorted from W and D.
    """
    N = range(n)
    H = [(u, v) for u in N for v in N if u != v]

    C: Dict[Tuple[int, int], List[float]] = {}
    K: Dict[Tuple[int, int], int] = {}
    L: Dict[Tuple[int, int], Dict[int, List[Tuple[int, int]]]] = {}
    cost_map: Dict[Tuple[int, int], Dict[Tuple[int, int], float]] = {}
    arcs_sorted: Dict[Tuple[int, int], List[Tuple[int, int]]] = {}

    for i in N:
        for j in N:
            if i == j:
                continue

            costs_ij = []
            cm = {}

            for u in N:
                for v in N:
                    if u == v:
                        continue

                    cost_uv = W[i][j] * (D[i][u] + D[u][v] + D[v][j])
                    costs_ij.append(cost_uv)
                    cm[(u, v)] = cost_uv

            unique_costs = sorted(set(round(c, 8) for c in costs_ij))

            C[(i, j)] = unique_costs
            K[(i, j)] = len(unique_costs)
            cost_map[(i, j)] = cm
            arcs_sorted[(i, j)] = sorted(cm.keys(), key=lambda a: cm[a])

            L[(i, j)] = {}
            for k_idx, target_cost in enumerate(unique_costs, start=1):
                arcs_k = [
                    (u, v)
                    for (u, v), c_val in cm.items()
                    if abs(c_val - target_cost) < 1e-8
                ]
                L[(i, j)][k_idx] = arcs_k

    od_pairs = [(i, j) for (i, j) in K if i != j and K[(i, j)] > 1]

    return H, C, L, K, cost_map, arcs_sorted, od_pairs


# ============================================================
# 2. Basic utility functions
# ============================================================

def safe_mean(values):
    return sum(values) / len(values) if values else 0.0


def safe_std(values):
    if len(values) <= 1:
        return 0.0
    return statistics.pstdev(values)


def selected_arcs_from_y(y: Dict[Tuple[int, int], float], threshold: float = 0.5):
    return [a for a, val in y.items() if val > threshold]


def compute_total_solution_cost(
    n: int,
    y_sol: Dict[Tuple[int, int], float],
    C: Dict,
    K: Dict,
    cost_map: Dict,
    arcs_sorted: Dict,
):
    """Computes true allocation cost for a given y solution."""
    total = 0.0

    for (i, j), Kij in K.items():
        if i == j:
            continue

        if Kij == 1:
            total += C[(i, j)][0]
        else:
            total += compute_allocation_cost(
                i,
                j,
                y_sol,
                cost_map.get((i, j), {}),
                arcs_sorted.get((i, j), []),
            )

    return total


# ============================================================
# 3. Arc-level ML features
# ============================================================

def build_arc_feature(
    n: int,
    W: List[List[float]],
    D: List[List[float]],
    cost_map: Dict,
    arc: Tuple[int, int],
):
    u, v = arc

    costs = []
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            costs.append(cost_map[(i, j)][(u, v)])

    outgoing_flow_u = sum(W[u][j] for j in range(n) if j != u)
    incoming_flow_u = sum(W[i][u] for i in range(n) if i != u)
    outgoing_flow_v = sum(W[v][j] for j in range(n) if j != v)
    incoming_flow_v = sum(W[i][v] for i in range(n) if i != v)
    total_flow = sum(W[i][j] for i in range(n) for j in range(n) if i != j)

    return [
        float(u),
        float(v),
        float(D[u][v]),
        float(outgoing_flow_u),
        float(incoming_flow_u),
        float(outgoing_flow_v),
        float(incoming_flow_v),
        float(outgoing_flow_u + incoming_flow_u),
        float(outgoing_flow_v + incoming_flow_v),
        float(total_flow),
        float(min(costs)),
        float(max(costs)),
        float(safe_mean(costs)),
        float(safe_std(costs)),
    ]


def build_arc_dataset_from_solved_instances(training_instances: List[Dict[str, Any]]):
    X = []
    y = []

    for inst in training_instances:
        n = inst["n"]
        W = inst["W"]
        D = inst["D"]
        selected = set(tuple(a) for a in inst["selected_arcs"])

        H, _, _, _, cost_map, _, _ = preprocess(n, W, D)

        for arc in H:
            X.append(build_arc_feature(n, W, D, cost_map, arc))
            y.append(1 if arc in selected else 0)

    return X, y


def train_arc_selection_model(
    training_instances: List[Dict[str, Any]],
    model_path: Optional[str] = None,
):
    if not SKLEARN_AVAILABLE:
        raise ImportError(
            "scikit-learn is not installed. Install: pip install scikit-learn joblib"
        )

    X, y = build_arc_dataset_from_solved_instances(training_instances)

    if len(set(y)) < 2:
        raise ValueError(
            "Training labels contain only one class. "
            "Need both selected and non-selected arcs in training data."
        )

    model = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            (
                "rf",
                RandomForestClassifier(
                    n_estimators=300,
                    max_depth=None,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=42,
                ),
            ),
        ]
    )

    model.fit(X, y)

    if model_path is not None:
        joblib.dump(model, model_path)

    return model


def load_ml_model(model_path: str):
    if not SKLEARN_AVAILABLE:
        raise ImportError("joblib / scikit-learn is not installed.")
    return joblib.load(model_path)


# ============================================================
# 4. ML warm start
# ============================================================

def predict_arc_scores(
    n: int,
    W: List[List[float]],
    D: List[List[float]],
    H: List[Tuple[int, int]],
    cost_map: Dict,
    arc_model=None,
):
    scores = {}

    if arc_model is not None:
        for arc in H:
            x = [build_arc_feature(n, W, D, cost_map, arc)]
            try:
                prob = arc_model.predict_proba(x)[0][1]
            except Exception:
                prob = float(arc_model.predict(x)[0])
            scores[arc] = float(prob)
    else:
        for arc in H:
            costs = [
                cost_map[(i, j)][arc]
                for i in range(n)
                for j in range(n)
                if i != j
            ]
            scores[arc] = -safe_mean(costs)

    return scores


def build_ml_warm_start(
    n: int,
    p: int,
    W: List[List[float]],
    D: List[List[float]],
    H: List[Tuple[int, int]],
    cost_map: Dict,
    arc_model=None,
):
    scores = predict_arc_scores(n, W, D, H, cost_map, arc_model)
    ranked_arcs = sorted(H, key=lambda a: scores[a], reverse=True)
    chosen = set(ranked_arcs[:p])
    y_ml = {a: 1.0 if a in chosen else 0.0 for a in H}
    return y_ml, scores


# ============================================================
# 5. OD-pair features for ML separation ranking
# ============================================================

def best_selected_cost_for_od(
    pair: Tuple[int, int],
    y_bar: Dict[Tuple[int, int], float],
    arcs_sorted: Dict,
    cost_map: Dict,
):
    i, j = pair
    for arc in arcs_sorted[(i, j)]:
        if y_bar.get(arc, 0.0) > 0.5:
            return cost_map[(i, j)][arc]
    return max(cost_map[(i, j)].values())


def build_od_feature(
    n: int,
    W: List[List[float]],
    D: List[List[float]],
    C: Dict,
    K: Dict,
    cost_map: Dict,
    arcs_sorted: Dict,
    pair: Tuple[int, int],
    y_bar: Dict[Tuple[int, int], float],
    theta_bar: Dict[Tuple[int, int], float],
):
    i, j = pair
    costs = C[(i, j)]
    theta_val = theta_bar.get((i, j), 0.0)
    best_cost = best_selected_cost_for_od(pair, y_bar, arcs_sorted, cost_map)
    violation_proxy = max(0.0, best_cost - theta_val)

    return [
        float(i),
        float(j),
        float(W[i][j]),
        float(D[i][j]),
        float(K[(i, j)]),
        float(min(costs)),
        float(max(costs)),
        float(safe_mean(costs)),
        float(safe_std(costs)),
        float(theta_val),
        float(best_cost),
        float(violation_proxy),
    ]


def rank_od_pairs(
    n: int,
    W: List[List[float]],
    D: List[List[float]],
    C: Dict,
    K: Dict,
    cost_map: Dict,
    arcs_sorted: Dict,
    od_pairs: List[Tuple[int, int]],
    y_bar: Dict[Tuple[int, int], float],
    theta_bar: Dict[Tuple[int, int], float],
    od_model=None,
):
    scored = []

    for pair in od_pairs:
        x = build_od_feature(
            n, W, D, C, K, cost_map, arcs_sorted, pair, y_bar, theta_bar
        )

        if od_model is not None:
            try:
                score = od_model.predict_proba([x])[0][1]
            except Exception:
                score = float(od_model.predict([x])[0])
        else:
            score = x[-1]

        scored.append((pair, float(score)))

    scored.sort(key=lambda item: item[1], reverse=True)
    return [pair for pair, _ in scored]


# ============================================================
# 6. Optional OD model training
# ============================================================

def train_od_pair_model(
    od_training_records: List[Dict[str, Any]],
    model_path: Optional[str] = None,
):
    if not SKLEARN_AVAILABLE:
        raise ImportError(
            "scikit-learn is not installed. Install: pip install scikit-learn joblib"
        )

    X = [r["features"] for r in od_training_records]
    y = [r["label"] for r in od_training_records]

    if len(set(y)) < 2:
        raise ValueError(
            "OD training labels contain only one class. "
            "Need both violated and non-violated examples."
        )

    model = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            (
                "rf",
                RandomForestClassifier(
                    n_estimators=300,
                    max_depth=None,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=42,
                ),
            ),
        ]
    )

    model.fit(X, y)

    if model_path is not None:
        joblib.dump(model, model_path)

    return model


# ============================================================
# 7. Cut expression builder
# ============================================================

def build_benders_cut_expr(cut_data: Dict[str, Any], y_vars: Dict):
    Ki = cut_data["Ki"]
    C1 = cut_data["C1"]
    nu = cut_data["nu"]

    expr = C1

    if nu.get(1, 0.0) != 0.0 and cut_data.get("L1"):
        expr += nu[1] * (1.0 - gp.quicksum(y_vars[a] for a in cut_data["L1"]))

    for k in range(2, Ki + 1):
        Lk = cut_data.get(f"L{k}", [])
        if nu.get(k, 0.0) != 0.0 and Lk:
            expr -= nu[k] * gp.quicksum(y_vars[a] for a in Lk)

    return expr


def cut_violation_score(cut_data: Dict[str, Any]):
    nu = cut_data.get("nu", {})
    nonzero_nu = [abs(v) for v in nu.values() if abs(v) > 1e-9]
    score = abs(cut_data.get("C1", 0.0))
    score += sum(nonzero_nu)
    score += len(nonzero_nu)
    return score


# ============================================================
# 8. ML-assisted Benders callback
# ============================================================

class MLBendersCutCallback:
    """
    Lazy constraint callback for ML-assisted Branch-and-Benders-cut.

    Exactness is preserved by fallback separation when the prioritized subset
    finds no cuts. For validation against standard Benders, use
    ml_pair_fraction=1.0 and max_cuts_per_callback=None.
    """

    def __init__(
        self,
        n: int,
        W: List[List[float]],
        D: List[List[float]],
        C: Dict,
        L: Dict,
        K: Dict,
        cost_map: Dict,
        arcs_sorted: Dict,
        od_pairs: List[Tuple[int, int]],
        y_vars: Dict,
        theta_vars: Dict,
        od_model=None,
        max_ml_pairs: Optional[int] = None,
        ml_pair_fraction: float = 0.25,
        max_cuts_per_callback: Optional[int] = None,
        collect_od_training_data: bool = False,
    ):
        self.n = n
        self.W = W
        self.D = D
        self.C = C
        self.L = L
        self.K = K
        self.cost_map = cost_map
        self.arcs_sorted = arcs_sorted
        self.od_pairs = od_pairs
        self.y_vars = y_vars
        self.theta_vars = theta_vars
        self.od_model = od_model

        self.max_ml_pairs = max_ml_pairs
        self.ml_pair_fraction = ml_pair_fraction
        self.max_cuts_per_callback = max_cuts_per_callback

        self.collect_od_training_data = collect_od_training_data
        self.od_training_records = []

        self.callback_count = 0
        self.total_lazy_cuts = 0
        self.full_fallback_calls = 0

    def _choose_ml_pairs(self, ranked_pairs):
        if self.max_ml_pairs is not None:
            q = min(self.max_ml_pairs, len(ranked_pairs))
        else:
            q = max(1, int(math.ceil(self.ml_pair_fraction * len(ranked_pairs))))
        return ranked_pairs[:q]

    def _add_cuts(self, model, cuts):
        if not cuts:
            return 0

        ranked_cuts = sorted(
            cuts,
            key=lambda item: cut_violation_score(item[1]),
            reverse=True,
        )

        if self.max_cuts_per_callback is not None:
            ranked_cuts = ranked_cuts[: self.max_cuts_per_callback]

        if len(ranked_cuts) == 0 and len(cuts) > 0:
            ranked_cuts = [cuts[0]]

        added = 0
        for ((i, j), cut_data) in ranked_cuts:
            expr = build_benders_cut_expr(cut_data, self.y_vars)
            model.cbLazy(self.theta_vars[(i, j)] >= expr)
            added += 1

        self.total_lazy_cuts += added
        return added

    def _collect_training_records(self, y_bar, theta_bar, violated_pairs_set):
        if not self.collect_od_training_data:
            return

        for pair in self.od_pairs:
            x = build_od_feature(
                self.n,
                self.W,
                self.D,
                self.C,
                self.K,
                self.cost_map,
                self.arcs_sorted,
                pair,
                y_bar,
                theta_bar,
            )
            label = 1 if pair in violated_pairs_set else 0
            self.od_training_records.append({"features": x, "label": label})

    def __call__(self, model, where):
        if where != GRB.Callback.MIPSOL:
            return

        self.callback_count += 1

        y_bar = {a: model.cbGetSolution(self.y_vars[a]) for a in self.y_vars}
        theta_bar = {
            (i, j): model.cbGetSolution(self.theta_vars[(i, j)])
            for (i, j) in self.theta_vars
        }

        ranked_pairs = rank_od_pairs(
            self.n,
            self.W,
            self.D,
            self.C,
            self.K,
            self.cost_map,
            self.arcs_sorted,
            self.od_pairs,
            y_bar,
            theta_bar,
            self.od_model,
        )

        ml_pairs = self._choose_ml_pairs(ranked_pairs)

        cuts, _ = separation_algorithm_dual(
            y_bar, theta_bar, self.C, self.L, self.K, ml_pairs
        )

        if cuts:
            violated_pairs_set = set(pair for pair, _ in cuts)
            self._collect_training_records(y_bar, theta_bar, violated_pairs_set)
            self._add_cuts(model, cuts)
            return

        self.full_fallback_calls += 1

        full_cuts, _ = separation_algorithm_dual(
            y_bar, theta_bar, self.C, self.L, self.K, self.od_pairs
        )

        violated_pairs_set = set(pair for pair, _ in full_cuts)
        self._collect_training_records(y_bar, theta_bar, violated_pairs_set)

        if full_cuts:
            self._add_cuts(model, full_cuts)


# ============================================================
# 9. Full ML-assisted Benders solver
# ============================================================

def solve_ml_benders_hub_arc(
    n: int,
    p: int,
    W: List[List[float]],
    D: List[List[float]],
    time_limit: Optional[float] = None,
    verbose: bool = False,
    use_phase1: bool = True,
    arc_model=None,
    od_model=None,
    max_ml_pairs: Optional[int] = None,
    ml_pair_fraction: float = 0.25,
    max_cuts_per_callback: Optional[int] = None,
    collect_od_training_data: bool = False,
) -> Dict[str, Any]:
    """Solve p-Hub-Arc using ML-assisted Benders decomposition."""
    start_time = time.time()

    H, C, L, K, cost_map, arcs_sorted, od_pairs = preprocess(n, W, D)

    y_ml, _ = build_ml_warm_start(
        n=n, p=p, W=W, D=D, H=H, cost_map=cost_map, arc_model=arc_model
    )

    UB_ml = compute_total_solution_cost(
        n=n, y_sol=y_ml, C=C, K=K, cost_map=cost_map, arcs_sorted=arcs_sorted
    )

    if verbose:
        print("ML warm start selected arcs:", selected_arcs_from_y(y_ml))
        print(f"ML warm start UB = {UB_ml:.6f}")

    y_start = y_ml
    phase1_info = {"phase1_used": False, "phase1_LB": None, "phase1_UB": None}

    if use_phase1:
        if verbose:
            print("\nPhase 1: Solving LP relaxation with ML warm start...")

        LB1, y1, UB1, _, _, _ = phase1_solve_mp(
            n,
            p,
            H,
            C,
            L,
            K,
            od_pairs,
            cost_map,
            arcs_sorted,
            y_heuristic=y_ml,
            UB_heuristic=UB_ml,
            verbose=verbose,
        )

        phase1_info = {"phase1_used": True, "phase1_LB": LB1, "phase1_UB": UB1}

        if y1:
            y_start = {a: 1.0 if y1.get(a, 0) > 0.5 else 0.0 for a in H}

        if verbose:
            print(f"Phase 1 done: LB={LB1:.6f}, UB={UB1:.6f}")

    if verbose:
        print("\nPhase 2: Branch-and-Benders-cut with ML callback...")

    model = gp.Model("ML_HubArc_Phase2")
    model.Params.OutputFlag = 1 if verbose else 0
    model.Params.LazyConstraints = 1
    model.Params.MIPGap = 1e-9

    if time_limit is not None:
        remaining_time = max(0.0, time_limit - (time.time() - start_time))
        model.Params.TimeLimit = remaining_time

    y_vars = {a: model.addVar(vtype=GRB.BINARY, name=f"y_{a[0]}_{a[1]}") for a in H}
    theta_vars = {
        (i, j): model.addVar(lb=0.0, vtype=GRB.CONTINUOUS, name=f"theta_{i}_{j}")
        for (i, j) in od_pairs
    }

    model.setObjective(
        gp.quicksum(theta_vars[(i, j)] for (i, j) in od_pairs),
        GRB.MINIMIZE,
    )
    model.addConstr(gp.quicksum(y_vars[a] for a in H) == p, name="p_hub_arcs")

    for a in H:
        y_vars[a].Start = y_start.get(a, 0.0)

    callback = MLBendersCutCallback(
        n=n,
        W=W,
        D=D,
        C=C,
        L=L,
        K=K,
        cost_map=cost_map,
        arcs_sorted=arcs_sorted,
        od_pairs=od_pairs,
        y_vars=y_vars,
        theta_vars=theta_vars,
        od_model=od_model,
        max_ml_pairs=max_ml_pairs,
        ml_pair_fraction=ml_pair_fraction,
        max_cuts_per_callback=max_cuts_per_callback,
        collect_od_training_data=collect_od_training_data,
    )

    model.optimize(callback)

    elapsed = time.time() - start_time
    has_sol = model.SolCount > 0

    diag = {
        "has_incumbent": has_sol,
        "incumbent_objective": model.ObjVal if has_sol else None,
        "obj_bound": model.ObjBound if has_sol else None,
        "mip_gap": model.MIPGap if has_sol else None,
        "callback_count": callback.callback_count,
        "lazy_cuts_added": callback.total_lazy_cuts,
        "full_fallback_calls": callback.full_fallback_calls,
        "od_training_records": callback.od_training_records
        if collect_od_training_data
        else None,
        **phase1_info,
    }

    if model.status in (GRB.OPTIMAL, GRB.TIME_LIMIT) and has_sol:
        y_sol = {a: y_vars[a].X for a in H}
        selected = [(u, v) for (u, v) in H if y_sol[(u, v)] > 0.5]
        obj = model.ObjVal
        for (i, j) in K:
            if i != j and K[(i, j)] == 1:
                obj += C[(i, j)][0]

        return {
            "objective": obj,
            "selected_arcs": selected,
            "time": elapsed,
            "status": "OPTIMAL" if model.status == GRB.OPTIMAL else "TIME_LIMIT",
            **diag,
        }

    return {
        "objective": diag["incumbent_objective"],
        "selected_arcs": None,
        "time": elapsed,
        "status": model.status,
        **diag,
    }
